### ISSUE TITLE
My Work is too bad

### ISSUE THREAD

**Issue by NilsHoyer** [bonecode/BCEditor#77]
I overtook this bonecode account from Lasse more than one year before and I cleaned up to code of him. Unfortunately, my work was very bad - much to much bugs. I my external project I steped back to SynEdit and I don't  plan to provide the BCEditor further more.

Is there somebody who want's to overtake this project?

**Comment by ValeriyTitov** [comment]
Can you list some bugs you have ?
I reported all i had. For me it works fine for now.

**Comment by NilsHoyer** [comment]
I have a "main" project with 300 Download per day. I implemented the latest work of BCEditor there, since I thought it would be nice. But I received several access violations, lines which are not shown, error messages from Windows API calls and so on. All of them, I don't know how to reproduce - so I switched back to SynEdit.

From my point of view, there are too less feedback for the BCEditor project - so I don't see the sense to work on this project if nobody use it.

Maybe somebody else wants to go ahead with my work, or wants to apply the work of Lasse (the initial developer of the BCEditor). My time is over on this project.

**Comment by ValeriyTitov** [comment]
Well, 2nd link on google with "delphi syntax edit" lead me here.
With some issues, i found what i want.
I think it's good.

**Comment by ValeriyTitov** [comment]
I don't understand, what does it mean - overtake BC Editor?
Also, i don't fully understand how does GitHub work and meaning all of this.

**Comment by NilsHoyer** [comment]
I don't provide this project further more. If you want to develop and support it up from now, I could give you the bonecode GitHub account. Than you can make what ever you want.

**Comment by shcham** [comment]
We use this component in some middle-to-big project,  with 300+ active users. It works, but still have some minor bugs.

**Comment by timofeevka** [comment]
Hi Nils !  We use this component in our project. I corresponded with Lasse at 2016 year - i insert my fixes into this code (for integration with our system). I our project all work fine. We use version from 01.06.2016, and it stable work with Delphi 10.2.3.

**Comment by Dimonka2** [comment]
I also have one of the versions of editor from 2016-2017 and I am very happy with it. 
SynEdit is just not really comparable with it. Sad that it got abandoned.

**Comment by Kashaket** [comment]
> Maybe you are the right one to overtake the BCEditor?

@NilsHoyer Hello, i can take it... and, i think this project must have some wiki, just for contributors, at the start - for people who want make it better, but not to take all of the work on themselves.

Maybe i'm not the best developer, i also had a lot of bugs in the rewrited code, but... three controls, which i've updated, become more stable, so, i think,  i can do something...
I do not have much experience in Lazarus, so, it throws errors in most cases, but, i have enough experience in Delphi to debug and stabilize the project, i think...
